apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: baseusers.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: BaseUser
    listKind: BaseUserList
    plural: baseusers
    singular: baseuser
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BaseUser is the Schema for the baseusers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BaseUserSpec defines the desired state of BaseUser
            properties:
              department_id:
                type: string
              display:
                type: string
              email:
                type: string
              name:
                type: string
              password:
                type: string
              roles:
                items:
                  type: string
                type: array
            type: object
          status:
            description: BaseUserStatus defines the observed state of BaseUser
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
