apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tektongraphs.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: TektonGraph
    listKind: TektonGraphList
    plural: tektongraphs
    singular: tektongraph
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TektonGraph is the Schema for the tektongraphs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/action-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TektonGraphSpec defines the desired state of TektonGraph
            properties:
              data:
                type: string
              height:
                format: int32
                type: integer
              width:
                format: int32
                type: integer
            type: object
          status:
            description: TektonGraphStatus defines the observed state of TektonGraph
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
