#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: yamecloud
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      name: yamecloud
#  template:
#    metadata:
#      labels:
#        name: yamecloud
#    spec:
#      serviceAccountName: yamecloud
#      containers:
#        - name: yamecloud
#          # Replace this with the built image name
#          image: REPLACE_IMAGE
#          command:
#          - yamecloud
#          imagePullPolicy: Always
#          env:
#            - name: WATCH_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: OPERATOR_NAME
#              value: "yamecloud"
